services:

  db:
    image: postgres:16

    container_name: smart-monitor-db

    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-smartadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env}
      POSTGRES_DB: ${POSTGRES_DB:-smart_monitor}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5433:5432"


  backend:

    build: .

    container_name: smart-monitor-api

    restart: always

    depends_on:
      - db

    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY:?set SECRET_KEY in .env}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-60}

    ports:
      - "8000:8000"


volumes:

  postgres_data:
